openapi: 3.1.0

info:
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0

paths:
  /users:
    get:
      summary: Retrieve a list of users
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 2
          maxLength: 80
        email:
          type: string
          format: email